//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace IMIC.VALUEOBJECTS
{
    public class Classes
    {
        public int Id { get; set; }
        public string ClassName { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<int> NumberStudents { get; set; }
        public string PlaceTraining { get; set; }
        public Nullable<int> ExpertId { get; set; }
        public Nullable<int> CenterId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<double> TotalPrice { get; set; }
    }
}
