//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace IMIC.VALUEOBJECTS
{    
    public class CommentSupport
    {
        public int Id { get; set; }
        public string CommentName { get; set; }
        public string Desription { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateLastUpdate { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string Notes { get; set; }
        public byte Flag { get; set; }
    }
}
