//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS.Models
{
    public class iMICYoutube
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string URL { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<int> Status { get; set; }
        public string Sources { get; set; }
        public string Description { get; set; }
    }
}
