//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace IMIC.VALUEOBJECTS.Models
{
    public class iScheduleExpertInfo
    {
        public long Id { get; set; }
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> ExpertId { get; set; }
        public Nullable<int> CourseId { get; set; }
        public string DayOf { get; set; }
        public string DayOfWeed { get; set; }
        public string TimeOf { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
