//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{
    public class Ou
    {
        public int Id { get; set; }
        public string OuName { get; set; }
        public string Avatar { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string Description { get; set; }
        public string OuCode { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public Nullable<int> ProvinceId { get; set; }
    }
}
