//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace IMIC.VALUEOBJECTS
{
    public class Software
    {
        public int Id { get; set; }
        public string SoftwareName { get; set; }
        public string Description { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateLastUpdate { get; set; }
        public Nullable<System.DateTime> DateCompleted { get; set; }
        public string Contents { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
    }
}
