//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{
    public class stanfMailSent
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string MailContent { get; set; }
        public string ReceiveList { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string AccountName { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<System.DateTime> DateLastUpdate { get; set; }
        public string Bcc { get; set; }
        public string Cc { get; set; }
        public string AttachFile { get; set; }
        public Nullable<int> SignatureId { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public Nullable<int> TypeMail { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
