//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{    
    public class stanfLogSystem
    {
        public int Id { get; set; }
        public Nullable<int> EventId { get; set; }
        public string EventKey { get; set; }
        public string EventName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string FormName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string UserName { get; set; }
        public string ComputerName { get; set; }
        public string IP { get; set; }
    }
}
