//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

namespace IMIC.VALUEOBJECTS
{
    public class stanfConfiguration
    {
        public int Id { get; set; }
        public Nullable<int> MailSendAdminId { get; set; }
        public string Subject { get; set; }
        public Nullable<int> MailTemplateId { get; set; }
        public Nullable<int> SignatureId { get; set; }
        public Nullable<int> MailSendCount { get; set; }
        public string Cc { get; set; }
        public string Bcc { get; set; }
        public Nullable<bool> SendAuto { get; set; }
        public Nullable<bool> Everyday { get; set; }
        public string SetDay { get; set; }
        public Nullable<System.TimeSpan> SetHour { get; set; }
        public Nullable<int> MinuteNumber { get; set; }
        public string FileName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string SMTP { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
    }
}
