//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{
    public class StudentWork
    {
        public int Id { get; set; }
        public string TitleJobName { get; set; }
        public Nullable<int> TitleJobId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Description { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<double> SalaryMoney { get; set; }
        public Nullable<double> SalaryLevel { get; set; }
        public string SalaryDescription { get; set; }
        public Nullable<int> OuId { get; set; }
        public string OuName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
    }
}
