//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{
    public class tblAnswer
    {
        public long AID { get; set; }
        public Nullable<long> QID { get; set; }
        public string Answers { get; set; }
        public Nullable<byte> CreateBy { get; set; }
        public Nullable<byte> Accept { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Steps { get; set; }
    }
}
