//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{
    public class tblDetailFace
    {
        public int DetailId { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> FaceId { get; set; }
        public string Links { get; set; }
        public Nullable<long> MemberOf { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
