//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{
    public class tblFacebook
    {
        public int FaceId { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string FaceName { get; set; }
        public string MobileConf { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
