//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{
    public class tblForum
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Links { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Domain { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> NguoiTao { get; set; }
    }
}
