//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{
    public class tblQuestion
    {
        public long QID { get; set; }
        public string Questions { get; set; }
        public Nullable<byte> CourseID { get; set; }
        public Nullable<byte> Status { get; set; }
        public string Descriptions { get; set; }
    }
}
