//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
namespace IMIC.VALUEOBJECTS
{    
    public class tblTinhTrangChamSoc
    {
        public int TinhTrangChamSocId { get; set; }
        public string TenHocvien { get; set; }
        public string LoaiHocVien { get; set; }
        public string TenLop { get; set; }
        public string TinhTrang { get; set; }
        public string DanhGiaHocVien { get; set; }
        public string HuongChamSoc { get; set; }
        public string NhanUuDai { get; set; }
        public string DeXuat { get; set; }
    }
}
