//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMIC.WEBIMIC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class WEBIMICDBEntities : DbContext
    {
        //public WEBIMICDBEntities()
        //    : base("name=WEBIMICDBEntities")
        //{
        //}
        public WEBIMICDBEntities(string obj)
            : base(obj)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<WEB_IMIC_SP_RegisterDetail_GetForEtraining_Result> WEB_IMIC_SP_RegisterDetail_GetForEtraining()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<WEB_IMIC_SP_RegisterDetail_GetForEtraining_Result>("WEB_IMIC_SP_RegisterDetail_GetForEtraining");
        }
    
        public virtual int WEB_IMIC_SP_RegisterDetail_UpdateIsSeen(Nullable<System.Guid> registerPersonId)
        {
            var registerPersonIdParameter = registerPersonId.HasValue ?
                new ObjectParameter("RegisterPersonId", registerPersonId) :
                new ObjectParameter("RegisterPersonId", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("WEB_IMIC_SP_RegisterDetail_UpdateIsSeen", registerPersonIdParameter);
        }
    }
}
